spring:
  application:
    name: market-service

  config:
    import: "optional:configserver:http://${CONFIG_HOST:localhost}:8888"

  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
