spring:
  application:
    name: analysis-service

  # ★ 여기에 추가 ★
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  cloud:
    config:
      fail-fast: true
      uri: http://localhost:8888
  config:
    import: "optional:configserver:http://${CONFIG_HOST:localhost}:8888"
  profiles:
    active: default

upstage:
  api:
    key: ${UPSTAGE_API_KEY:}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1