spring:
  application:
    name: community-service

  config:
    import: "optional:configserver:http://${CONFIG_HOST:localhost}:8888"

  profiles:
    active: default

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

    sql:
      init:
        mode: always

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

logging:
  level:
    org.springframework.security: DEBUG