package com.esg.notificationservice.domain;

public enum NotificationType {
  ORDER_COMPLETED,
  CANCELED_BY_ADMIN,
  CANCELED_BY_MEMBER,
  POINT_EARNED,
  POINT_USED,
  POINT_REFUNDED,
  ACTIVITY_PENDING,
  ACTIVITY_APPROVED,
  ACTIVITY_REJECTED,
  BADGE_EARNED,
  UNKNOWN
}
