name: Build and Push Docker Images

on:
  push:
    branches:
      - main


jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - analysis-service
          - auth-service
          - community-service
          - config-service
          - eureka-service
          - gateway-service
          - market-service
          - notification-service
          - point-service


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: esgplatform/${{ matrix.service }}:latest

  frontend-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./esg-platform-ui
          file: ./esg-platform-ui/Dockerfile
          push: true
          tags: esgplatform/esg-frontend:latest

  deploy-server1:
    needs: [docker-build-push, frontend-build-push]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server 1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER1_HOST }}
          username: ${{ secrets.SERVER1_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/ubuntu/esg-deploy
            docker compose pull
            docker compose up -d

  deploy-server2:
    needs: deploy-server1
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server 2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER2_HOST }}
          username: ${{ secrets.SERVER2_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/ubuntu/esg-deploy
            docker compose pull
            docker compose up -d